/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsExistsIndex {
  /** Build from a QvdTable column. */
  static fromColumn(table: JsQvdTable, colName: string): JsExistsIndex
  /** Build from an explicit list of values. */
  static fromValues(values: Array<string>): JsExistsIndex
  /** Check if a value exists (O(1)). */
  exists(value: string): boolean
  /** Check multiple values. */
  existsMany(values: Array<string>): Array<boolean>
  /** Number of unique values. */
  get len(): number
  /** Whether the index is empty. */
  get isEmpty(): boolean
}

export declare class JsQvdTable {
  /** Number of rows (safe for QVD files — Qlik limits tables to ~2B rows). */
  get numRows(): number
  /** Number of columns. */
  get numCols(): number
  /** Table name from QVD metadata. */
  get tableName(): string
  /** Column names. */
  get columns(): Array<string>
  /** Get a single cell value by row and column index. */
  get(row: number, col: number): string | null
  /** Get a single cell value by row index and column name. */
  getByName(row: number, colName: string): string | null
  /** Get all values of a column by index. */
  columnValues(col: number): Array<string | undefined | null>
  /** Get all values of a column by name. */
  columnValuesByName(colName: string): Array<string | undefined | null>
  /** Convert to an array of row objects: [{col1: val1, col2: val2, ...}, ...] */
  toJson(): Array<any>
  /** Get first N rows as array of objects. */
  head(n?: number | undefined | null): Array<any>
  /** Get unique symbols for a column. */
  symbols(colName: string): Array<string>
  /** Number of unique symbols in a column. */
  numSymbols(colName: string): number
  /** Filter rows where column matches any of the given values. */
  filterByValues(colName: string, values: Array<string>): JsQvdTable
  /** Create a new table from a subset of row indices. */
  subsetRows(rowIndices: Array<number>): JsQvdTable
  /** Normalize for maximum Qlik Sense compatibility. */
  normalize(): void
  /** Concatenate with another table (pure append). */
  concatenate(other: JsQvdTable, schema?: string | undefined | null): JsQvdTable
  /** Concatenate with PK-based deduplication. */
  concatenatePk(other: JsQvdTable, pk: Array<string>, onConflict?: string | undefined | null, schema?: string | undefined | null): JsQvdTable
}

/** Concatenate two QVD files with PK dedup and write result. Returns Promise<void>. */
export declare function concatenatePkQvd(pathA: string, pathB: string, outputPath: string, pk: Array<string>, onConflict?: string | undefined | null, schema?: string | undefined | null): Promise<void>

/** Concatenate two QVD files and write result. Returns Promise<void>. */
export declare function concatenateQvd(pathA: string, pathB: string, outputPath: string, schema?: string | undefined | null): Promise<void>

/** Filter rows where column value exists in the index. Returns matching row indices. */
export declare function filterExists(table: JsQvdTable, colName: string, index: JsExistsIndex): Array<number>

/** Read a QVD file asynchronously. Returns Promise<QvdTable>. */
export declare function readQvd(path: string): Promise<JsQvdTable>

/** Read QVD with streaming EXISTS() filter. Returns Promise<QvdTable>. */
export declare function readQvdFiltered(path: string, filterCol: string, values: Array<string>, select?: Array<string> | undefined | null, chunkSize?: number | undefined | null): Promise<JsQvdTable>

/** Read a QVD file synchronously (blocks the event loop — use for scripts/CLI). */
export declare function readQvdSync(path: string): JsQvdTable

/** Save a QvdTable to a file asynchronously. Returns Promise<void>. */
export declare function saveQvd(table: JsQvdTable, path: string): Promise<void>

/** Save a QvdTable to a file synchronously. */
export declare function saveQvdSync(table: JsQvdTable, path: string): void
