/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Fast O(1) lookup index over a set of string values.
 *
 * Used by {@link filterExists} and by the streaming entry point
 * {@link readQvdFiltered}. Build either from a {@link JsQvdTable} column via
 * {@link JsExistsIndex.fromColumn}, or from an explicit list via
 * {@link JsExistsIndex.fromValues}.
 */
export declare class JsExistsIndex {
  /**
   * Build a {@link JsExistsIndex} from a {@link JsQvdTable} column.
   *
   * @param table - Source table.
   * @param colName - Column to index.
   * @returns New index containing the column's distinct values.
   * @throws If `colName` is not a column of `table`.
   *
   * @example
   * ```typescript
   * const idx = JsExistsIndex.fromColumn(table, "ClientID");
   * ```
   */
  static fromColumn(table: JsQvdTable, colName: string): JsExistsIndex
  /**
   * Build a {@link JsExistsIndex} from an explicit list of values.
   *
   * @param values - Values to index. Duplicates are deduplicated.
   * @returns New index containing the provided values.
   *
   * @example
   * ```typescript
   * const idx = JsExistsIndex.fromValues(["7", "9"]);
   * ```
   */
  static fromValues(values: Array<string>): JsExistsIndex
  /**
   * Check whether a single value is in the index.
   *
   * O(1) hash lookup.
   *
   * @param value - Value to look up.
   * @returns `true` if present, otherwise `false`.
   */
  exists(value: string): boolean
  /**
   * Check multiple values at once.
   *
   * @param values - Values to look up.
   * @returns One flag per input value, in the same order.
   */
  existsMany(values: Array<string>): Array<boolean>
  /**
   * Number of unique values in the index.
   *
   * @returns Unique value count.
   */
  get len(): number
  /**
   * Whether the index is empty.
   *
   * @returns `true` if the index contains no values.
   */
  get isEmpty(): boolean
}

/**
 * In-memory representation of a QVD file.
 *
 * Load via {@link readQvd} (async) or {@link readQvdSync}, persist via
 * {@link saveQvd}/{@link saveQvdSync}. Use the `columnValues*` / `toJson` /
 * `head` methods to inspect data, and `concatenate*` / `filterByValues` /
 * `subsetRows` to derive new tables without mutating the source.
 */
export declare class JsQvdTable {
  /**
   * Number of rows in the table.
   *
   * Safe as a `u32` — Qlik limits QVD tables to ~2 billion rows.
   *
   * @returns Row count.
   */
  get numRows(): number
  /**
   * Number of columns in the table.
   *
   * @returns Column count.
   */
  get numCols(): number
  /**
   * Table name as stored in the QVD header metadata.
   *
   * @returns Table name.
   */
  get tableName(): string
  /**
   * Column names in declaration order.
   *
   * @returns Column names.
   */
  get columns(): Array<string>
  /**
   * Get a single cell value by row and column index.
   *
   * @param row - Zero-based row index.
   * @param col - Zero-based column index.
   * @returns Cell value as string, or `null` for NULL.
   * @throws If `row` or `col` is out of bounds.
   */
  get(row: number, col: number): string | null
  /**
   * Get a single cell value by row index and column name.
   *
   * @param row - Zero-based row index.
   * @param colName - Column name.
   * @returns Cell value as string, or `null` for NULL.
   * @throws If `colName` does not exist in the table.
   */
  getByName(row: number, colName: string): string | null
  /**
   * Get all values of a column by index.
   *
   * @param col - Zero-based column index.
   * @returns Column values, with `null` for NULL.
   * @throws If `col` is out of bounds.
   */
  columnValues(col: number): Array<string | undefined | null>
  /**
   * Get all values of a column by name.
   *
   * @param colName - Column name.
   * @returns Column values, with `null` for NULL.
   * @throws If `colName` does not exist in the table.
   */
  columnValuesByName(colName: string): Array<string | undefined | null>
  /**
   * Convert the table to an array of row objects.
   *
   * Each row is rendered as `{ columnName: value | null, ... }`.
   *
   * @returns One object per row, keyed by column name.
   *
   * @example
   * ```typescript
   * const rows = table.toJson();
   * // [{ Country: "DE", Sales: "100" }, ...]
   * ```
   */
  toJson(): Array<any>
  /**
   * Return the first `n` rows as an array of objects.
   *
   * @param n - Number of rows to return. Defaults to `10`. Capped at the
   * table's row count.
   * @returns One object per row, keyed by column name.
   */
  head(n?: number | undefined | null): Array<any>
  /**
   * Get the unique symbols (distinct values) of a column.
   *
   * @param colName - Column name.
   * @returns Distinct symbol values in QVD storage order.
   * @throws If `colName` does not exist in the table.
   */
  symbols(colName: string): Array<string>
  /**
   * Number of unique symbols in a column.
   *
   * @param colName - Column name.
   * @returns Distinct symbol count.
   * @throws If `colName` does not exist in the table.
   */
  numSymbols(colName: string): number
  /**
   * Filter rows where a column value matches any of the given values.
   *
   * @param colName - Column to filter on.
   * @param values - Values that should be kept.
   * @returns New table containing only the matching rows. The source table
   * is not modified.
   *
   * @example
   * ```typescript
   * const filtered = table.filterByValues("%Action_ID", ["7", "9"]);
   * ```
   */
  filterByValues(colName: string, values: Array<string>): JsQvdTable
  /**
   * Create a new table from a subset of row indices.
   *
   * @param rowIndices - Zero-based row indices to keep, in the desired
   * output order. Indices may be repeated.
   * @returns New table containing only the selected rows.
   *
   * @example
   * ```typescript
   * const rows = filterExists(table, "ClientID", idx);
   * const subset = table.subsetRows(rows);
   * ```
   */
  subsetRows(rowIndices: Array<number>): JsQvdTable
  /**
   * Normalize the table for maximum Qlik Sense compatibility.
   *
   * Converts `DualInt` → `Int` and `DualDouble` → `Double` and sets proper
   * `NumberFormat`, `Tags` and `BitWidth` on each field. Modifies the table
   * in place.
   */
  normalize(): void
  /**
   * Concatenate another table into this one (pure append, no deduplication).
   *
   * @param other - Table whose rows are appended.
   * @param schema - `"strict"` errors on column mismatch, `"union"` fills
   * missing columns with NULL. Defaults to `"strict"`.
   * @returns New merged table. Inputs are not modified.
   * @throws On invalid `schema` value or column mismatch under `"strict"`.
   *
   * @example
   * ```typescript
   * const merged = tableA.concatenate(tableB);
   * const mergedUnion = tableA.concatenate(tableB, "union");
   * ```
   */
  concatenate(other: JsQvdTable, schema?: string | undefined | null): JsQvdTable
  /**
   * Concatenate another table with primary-key deduplication.
   *
   * @param other - Table whose rows are appended.
   * @param pk - Primary-key columns. Pass `[col]` for a single key or
   * `[col1, col2, ...]` for a composite key.
   * @param onConflict - Behaviour when a PK collision is detected.
   * `"replace"` lets new rows win, `"skip"` keeps existing rows, `"error"`
   * throws. Defaults to `"replace"`.
   * @param schema - `"strict"` errors on column mismatch, `"union"` fills
   * missing columns with NULL. Defaults to `"strict"`.
   * @returns New merged table. Inputs are not modified.
   * @throws On invalid `onConflict`/`schema` values, missing PK column, or
   * PK collision when `onConflict` is `"error"`.
   *
   * @example
   * ```typescript
   * const merged = existing.concatenatePk(newRows, ["orderId"]);
   * const skipped = existing.concatenatePk(
   *   newRows,
   *   ["a", "b"],
   *   "skip",
   *   "union",
   * );
   * ```
   */
  concatenatePk(other: JsQvdTable, pk: Array<string>, onConflict?: string | undefined | null, schema?: string | undefined | null): JsQvdTable
}

/**
 * Concatenate two QVD files asynchronously with primary-key deduplication.
 *
 * @param pathA - Path to the existing `.qvd` file.
 * @param pathB - Path to the file whose rows are appended.
 * @param outputPath - Destination `.qvd` path.
 * @param pk - Primary-key columns. Pass `[col]` for a single key or
 * `[col1, col2, ...]` for a composite key.
 * @param onConflict - Behaviour when a PK collision is detected.
 * `"replace"` lets new rows win, `"skip"` keeps existing rows, `"error"`
 * throws. Defaults to `"replace"`.
 * @param schema - `"strict"` errors on column mismatch, `"union"` fills
 * missing columns with NULL. Defaults to `"strict"`.
 * @returns Promise resolving when the merged file has been written.
 * @throws On invalid `onConflict`/`schema` values, unreadable input,
 * missing PK column, or PK collision when `onConflict` is `"error"`.
 *
 * @example
 * ```typescript
 * import { concatenatePkQvd } from "qvdrs";
 *
 * await concatenatePkQvd(
 *   "existing.qvd",
 *   "new.qvd",
 *   "out.qvd",
 *   ["orderId"],
 * );
 * ```
 */
export declare function concatenatePkQvd(pathA: string, pathB: string, outputPath: string, pk: Array<string>, onConflict?: string | undefined | null, schema?: string | undefined | null): Promise<void>

/**
 * Concatenate two QVD files into a new QVD file asynchronously (pure append).
 *
 * @param pathA - Path to the existing `.qvd` file.
 * @param pathB - Path to the file whose rows are appended.
 * @param outputPath - Destination `.qvd` path.
 * @param schema - `"strict"` errors on column mismatch, `"union"` fills
 * missing columns with NULL. Defaults to `"strict"`.
 * @returns Promise resolving when the merged file has been written.
 * @throws On invalid `schema`, unreadable input, or column mismatch under
 * `"strict"`.
 *
 * @example
 * ```typescript
 * import { concatenateQvd } from "qvdrs";
 *
 * await concatenateQvd("existing.qvd", "new_data.qvd", "merged.qvd");
 * ```
 */
export declare function concatenateQvd(pathA: string, pathB: string, outputPath: string, schema?: string | undefined | null): Promise<void>

/**
 * Filter rows where a column value is in a {@link JsExistsIndex}.
 *
 * @param table - Table to filter.
 * @param colName - Column to look up in `index`.
 * @param index - Lookup index.
 * @returns Row indices of matching rows, in ascending order.
 * @throws If `colName` is not a column of `table`.
 *
 * @example
 * ```typescript
 * const idx = JsExistsIndex.fromValues(["7", "9"]);
 * const rows = filterExists(table, "%Action_ID", idx);
 * const subset = table.subsetRows(rows);
 * ```
 */
export declare function filterExists(table: JsQvdTable, colName: string, index: JsExistsIndex): Array<number>

/**
 * Read a QVD file asynchronously.
 *
 * Resolves with a {@link JsQvdTable} loaded from disk. Heavy I/O runs on a
 * worker thread — the event loop stays free.
 *
 * @param path - Path to the `.qvd` file.
 * @returns Promise resolving to the loaded table.
 * @throws If the file cannot be opened or is not a valid QVD.
 *
 * @example
 * ```typescript
 * import { readQvd } from "qvdrs";
 *
 * const table = await readQvd("data.qvd");
 * console.log(table.numRows);
 * ```
 */
export declare function readQvd(path: string): Promise<JsQvdTable>

/**
 * Read a QVD file asynchronously with a streaming EXISTS() filter.
 *
 * Only matching rows are loaded into memory — much faster and lighter than
 * reading the entire file for large inputs.
 *
 * @param path - Path to the `.qvd` file.
 * @param filterCol - Column name to filter on.
 * @param values - Values to keep. A row is kept iff its `filterCol` value is
 * in this list.
 * @param select - Subset of columns to load. Pass `undefined` to load all
 * columns.
 * @param chunkSize - Streaming chunk size in rows. Defaults to `65536`.
 * @returns Promise resolving to a table containing only the matching rows.
 * @throws If the file cannot be read or `filterCol` does not exist.
 *
 * @example
 * ```typescript
 * import { readQvdFiltered } from "qvdrs";
 *
 * const table = await readQvdFiltered(
 *   "large.qvd",
 *   "%Action_ID",
 *   ["7", "9"],
 *   ["%Client_ID", "Date_BK", "%Action_ID"],
 * );
 * ```
 */
export declare function readQvdFiltered(path: string, filterCol: string, values: Array<string>, select?: Array<string> | undefined | null, chunkSize?: number | undefined | null): Promise<JsQvdTable>

/**
 * Read a QVD file synchronously.
 *
 * Blocks the event loop while the file is being read — use only for scripts
 * or CLIs. Prefer {@link readQvd} in servers.
 *
 * @param path - Path to the `.qvd` file.
 * @returns Loaded table.
 * @throws If the file cannot be opened or is not a valid QVD.
 */
export declare function readQvdSync(path: string): JsQvdTable

/**
 * Save a {@link JsQvdTable} to a file asynchronously.
 *
 * If the table has not been modified since loading, the output is a
 * byte-identical roundtrip of the source file.
 *
 * @param table - Table to persist.
 * @param path - Destination `.qvd` path.
 * @returns Promise resolving when the file has been written.
 * @throws If the file cannot be written.
 */
export declare function saveQvd(table: JsQvdTable, path: string): Promise<void>

/**
 * Save a {@link JsQvdTable} to a file synchronously.
 *
 * Blocks the event loop while writing. Prefer {@link saveQvd} in servers.
 *
 * @param table - Table to persist.
 * @param path - Destination `.qvd` path.
 * @throws If the file cannot be written.
 */
export declare function saveQvdSync(table: JsQvdTable, path: string): void
